# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: M 2.3 Grundlagen der Elektrotechnik (GEL2)
authors:
  - name: Mirco Meiners
    orcid: 0000-0002-9709-4191
    email: Mirco.Meiners@hs-bremen.de
    affiliations:
      - id: hsb
        institution: Hochschule Bremen - City University of Applied Sciences (HSB)
        department: Electrical Engineering and Computer Sciences
        city: Bremen
        country: Germany
        url: https://www.hs-bremen.de/person/mimeiners/
  - name: Alicia von Ahlen
    orcid: 0009-0007-3049-2455
    email: avahlen@stud.hs-bremen.de
    affiliation: hsb
license: "CC-BY-4.0"
copyright: "2024-2025"
logo: ./images/hsb-logo.png

exclude_patterns: ["LICENSE.md", "README.md"]

only_build_toc_files: true

# Short description about the book
description: >-
  Skriptum zum B.Eng. ET Modul GEL2 an der HSB.

# HTML-specific settings
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: true
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  navbar_number_sections: true
  baseurl: "https://mimeiners.github.io/gel2/"

  comments:
    hypothesis: true
    utterances:
      repo: "mimeiners/gel2"
      dokieli: true
  extra_footer : |
    <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
      <img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
      All content on this site (unless otherwise specified) is licensed under the 
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
    </div>


# LaTeX settings
bibtex_bibfiles:
  - _bibliography/references.bib
latex:
  latex_documents:
    targetname: gel2.tex

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  
repository:
  url: https://github.com/mimeiners/gel2

# Advanced and power-user settings
sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    html_show_copyright: true
    html_extra_path: ['files']
    language: de
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

    myst_enable_extensions: 
    - amsmath
    - dollarmath
    - colon_fence
    - deflist
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      INSTRUCTOR: "Prof. Dr.-Ing. Mirco Meiners (he/his/him)"
      OFFICE: "E 508"
      COURSE_CODE: "M 2.3"
      CREDITS: "6"
      TITLE: "Grundlagen der Elektrotechnik 2 (GEL2)"
      PREREQS: "GEL1"
      TERM: "SoSe2025"
      ROOM: "E 509"
      MEETING_TIMES: "Mo. 8:00 Uhr - 9:30 Uhr (Tutorium), 9:45 Uhr - 11:15 Uhr (Seminar)"
      FORMAT: "Seminar und Übungen"
      ASSOCIATE_HEAD: "Alicia von Ahlen [avahlen@stud.hs-bremen.de](mailto:avahlen@stud.hs-bremen.de)"
