project:
  type: book
  output-dir: _book
  
lang: de

book:
  title: "Grundlagen der Elektrotechnik 2"
  author:
    - name: Mirco Meiners
      orcid: 0000-0002-9709-4191
      email: Mirco.Meiners@hs-bremen.de
      corresponding: true
      roles: "Lead author"
      affiliation:
        - name: Hochschule Bremen - City University of Applied Sciences (HSB)
          city: Bremen
          state: Germany
          url: https://www.hs-bremen.de/person/mimeiners/ 
    - name: Alicia von Ahlen
      email: avahlen@stud.hs-bremen.de
      roles: "Supporting author"
  date: last-modified
  license: "Apache-2.0 license"

  reader-mode: true

  page-footer:
    left: |
      Grundlagen der Elektrotechnik 2 (GEL2), M. Meiners, HSB.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/hsb-logo.png
#  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/gel2/
  repo-url: https://github.com/mimeiners/gel2/
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf,epub]

  chapters:
    - index.qmd

    - part: Seminar
      chapters:
        - class/01_lec.qmd
        - class/02_lec.qmd
        - class/03_lec.ipynb
        - class/04_lec.qmd
        - class/05_lec.ipynb
        - class/06_lec.ipynb
        - class/07_lec.qmd
        - class/08_lec.qmd
    - part: Hörsaalübungen 
      chapters:
        - exercise/hw1.ipynb
        - exercise/hw2.ipynb
        - exercise/hw3.ipynb
        - exercise/hw4.ipynb
        - exercise/hw5.ipynb
        - exercise/hw6.ipynb
        - exercise/hw7.ipynb
    - part: Tutorium
      chapters:
        - Tutorium/1_Einfuehrung.qmd
        - Tutorium/2_Komplexe-Zahlen.ipynb
        - Tutorium/3_Periodische-Signale.ipynb
        - Tutorium/4_Komplexe-Groessen.ipynb
        - Tutorium/5_Grundzweipole1.ipynb
        - Tutorium/6_Grundzweipole2.ipynb
        - Tutorium/7_KWR.ipynb
        - Tutorium/8_Filterschaltungen.ipynb
        - Tutorium/9_Schwingkreise.ipynb
        - Tutorium/10_Transformatoren.ipynb
        - Tutorium/11_Klausurvorbereitung.ipynb

bibliography: _bibliography/references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrbook # scrreptrt
#    lof: true
#    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    #    keep-tex: true
    output-file: elk
  epub:
    theme: flatly
    output-file: elk
  
execute:
  freeze: auto

