project:
  type: book
  output-dir: _book
  
lang: de

book:
  title: "Grundlagen der Elektrotechnik 2"
  author:
    - name: "Mirco Meiners"
      orcid: "0000-0002-9709-4191"
      email: "Mirco.Meiners@hs-bremen.de"
      corresponding: true
      roles: "Lead author"
      affiliation:
        - id: hsb
        - name: "Hochschule Bremen - City University of Applied Sciences"
          city: "Bremen"
          state: "Germany"
          url: "https://www.hs-bremen.de/person/mimeiners/"
    - name: "Alicia von Ahlen"
      orcid: "0009-0007-3049-2455"
      email: "avahlen@stud.hs-bremen.de"
      roles: "Supporting author"
      affiliation:
        - ref: hsb

  date: last-modified

  #  license: "Apache-2.0 license"
  
  reader-mode: true

  page-footer:
    left: |
      Grundlagen der Elektrotechnik 2 (GEL2), M. Meiners, HSB.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/hsb-logo.png
  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/gel2/
  repo-url: https://github.com/mimeiners/gel2/
  repo-branch: quarto
  repo-actions: [edit,issue]
  downloads: [pdf]

  chapters:
    - index.qmd
    - part: Seminar
      chapters:
        - lec/lec_01.qmd
        - lec/lec_02.qmd
        - lec/lec_03.qmd
        - lec/lec_04.qmd
        - lec/lec_05.qmd
        - lec/lec_06.qmd
        - lec/lec_07.qmd
        - lec/lec_08.qmd
    - part: Hörsaalübungen 
      chapters:
        - hw/hw_00.qmd
        - hw/hw_01.qmd
#        - hw/hw_02.qmd
        - hw/hw_03.qmd
        - hw/hw_04.qmd
        - hw/hw_05.qmd
        - hw/hw_06.qmd
        - hw/hw_07.qmd
    - part: Tutorium
      chapters:
#        - tut/tut_01_Einfuehrung.qmd
        - tut/tut_02_Komplexe-Zahlen.ipynb
        - tut/tut_03_Periodische-Signale.qmd
        - tut/tut_04_Komplexe-Groessen.ipynb
        - tut/tut_05_Grundzweipole1.ipynb
        - tut/tut_06_Grundzweipole2.ipynb
        - tut/tut_07_KWR.ipynb
        - tut/tut_08_Filterschaltungen.ipynb
        - tut/tut_09_Schwingkreise.ipynb
        - tut/tut_10_Transformatoren.ipynb
        - tut/tut_11_Klausurvorbereitung1.ipynb
        - tut/tut_12_Klausurvorbereitung2.ipynb
    - references.qmd

  output-file: "gel2"

# Bibliography
bibliography: _bibliography/references.bib
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
# csl: _bibliography/ieee.csl

execute:
  freeze: true
  
format:
  
  html:
    theme: flatly
    fontsize: 1.2em
    linestretch: 1.7
    # mainfont: Verdana
    # monofont: Menlo
    # backgroundcolor: "white"
    # fontcolor: "black"
    highlight-style: github
    default-image-extension: svg

 # epub:
 #   theme: flatly
 #   fontsize: 1.2em
 #   linestretch: 1.7
 #   # mainfont: Helvetica Neue, Helvetica, Arial, sans
 #   # monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
 #   # backgroundcolor: "white"
 #   # fontcolor: "black"
 #   highlight-style: github
 #   default-image-extension: svg
 
  pdf:
    documentclass: scrbook
    classoption: [twoside]

    # keep-tex: true

    toc: true
    toc-depth: 3
    # toc-title: "Table of contents"
    # lof: true
    # lot: true

    number-sections: true
    number-depth: 2
        
    papersize: a4
    
    geometry:
      - inner=3cm
      - outer=4cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded

    fontsize: 11pt
    pdfengine: xelatex

    mainfont: "Calibri"
    monofont: "MesloLGS NF"
    mathfont: "TeX Gyre Termes Math"
    
  # include-in-header:
  #   - frontmatter/header.tex
  # template-partials:
  # - frontmatter/before-body.tex
  # - frontmatter/toc.tex
  
