project:
  type: book
  output-dir: _book
  
lang: de

book:
  title: "Grundlagen der Elektrotechnik 2"
  author:
    - name: Mirco Meiners
      orcid: 0000-0002-9709-4191
      email: Mirco.Meiners@hs-bremen.de
      corresponding: true
      roles: "Lead author"
      affiliation:
        - name: Hochschule Bremen - City University of Applied Sciences (HSB)
          city: Bremen
          state: Germany
          url: https://www.hs-bremen.de/person/mimeiners/ 
    - name: Alicia von Ahlen
      orcid: 0009-0007-3049-2455
      email: avahlen@stud.hs-bremen.de
      roles: "Supporting author"
  date: last-modified
  license: "Apache-2.0 license"

  reader-mode: true

  page-footer:
    left: |
      Grundlagen der Elektrotechnik 2 (GEL2), M. Meiners, HSB.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/hsb-logo.png
#  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/gel2/
  repo-url: https://github.com/mimeiners/gel2/
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf,epub]

  chapters:
    - index.qmd
    - part: Seminar
      chapters:
        - lec/lec_01.qmd
        - lec/lec_02.qmd
        - lec/lec_03.ipynb
        - lec/lec_04.qmd
        - lec/lec_05.ipynb
        - lec/lec_06.ipynb
        - lec/lec_07.qmd
        - lec/lec_08.qmd
    - part: Hörsaalübungen 
      chapters:
        - hw/hw_01.ipynb
        - hw/hw_02.ipynb
        - hw/hw_03.ipynb
        - hw/hw_04.ipynb
        - hw/hw_05.ipynb
        - hw/hw_06.ipynb
        - hw/hw_07.ipynb
    - part: Tutorium
      chapters:
        - tut/tut_01_Einfuehrung.qmd
        - tut/tut_02_Komplexe-Zahlen.ipynb
        - tut/tut_03_Periodische-Signale.ipynb
        - tut/tut_04_Komplexe-Groessen.ipynb
        - tut/tut_05_Grundzweipole1.ipynb
        - tut/tut_06_Grundzweipole2.ipynb
        - tut/tut_07_KWR.ipynb
        - tut/tut_08_Filterschaltungen.ipynb
        - tut/tut_09_Schwingkreise.ipynb
        - tut/tut_10_Transformatoren.ipynb
        - tut/tut_11_Klausurvorbereitung.ipynb
    - references.qmd
    
bibliography: _bibliography/references.bib

filters:
  - admonitions
  
format:
  html:
    theme: flatly
  pdf:
    documentlec: scrbook # scrreptrt
#    lof: true
#    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    #    keep-tex: true
    output-file: elk
  epub:
    theme: flatly
    output-file: elk
  
execute:
  freeze: auto

