# Einführung

## Organisatorisches

Tutor: **B.Eng. Alicia von Ahlen**

Zu meiner Person:
Ich habe Elektrotechnik mit der Vertiefungsrichtung Informationstechnik studiert und bin zur Zeit im 1. Semester des
Masterprogramms MScEE an der HSB. Ich habe bereits die Tutorien _Grundlagen der Elektrotechnik 1 und 2_ durchgeführt.

Das tut ist als Unterstützung zur Vorlesung gedacht und legt den Fokus auf eine Wiederholung der Unterrichtsinhalte
und Übungsaufgaben. Es besteht auch die Möglichkeit Fragen zu den Vorlesungsinhalten zu stellen und Wünsche zu äußern,
zum Beispiel auf welche Themen besonders Wert gelegt oder speziell wiederholt werden sollen.
Zur besseren Vorbereitung meinerseits, bitte ich darum, dass Themenwünsche und wenn möglich auch Fragen, mir im Vorfeld
per Email geschickt werden, damit ich genug Zeit habe, diese zu bearbeiten.

## Termine

**t.b.d.**

Das GEL2-tut findet montags im ersten Block (08:00 - 09:30 Uhr) statt.

Eine grobe Zeit- und Themenplanung ist in der folgenden Tabelle zu sehen. Dabei kann es durchaus sein, dass sich diese
Planung noch etwas ändert.

| Datum    | Thema                                          |
|:--------:|:-----------------------------------------------|
| 15.04.24 | Einführung & Komplexe Zahlen                   |
| 22.04.24 | Periodische Signale                            |
| 29.04.24 | Komplexe Größen der Sinusstromtechnik          |
| 06.05.24 | Verhalten der Grundzweipole 1                  |
| 13.05.24 | Verhalten der Grundzweipole 2                  |
| 20.05.24 | **Pfingstmontag**                              |
| 27.05.24 | KWR                                            |
| 03.06.24 | Filterschaltungen, Bodediagramm und Ortskurven |
| 10.06.24 | Schwingkreise                                  |
| 17.05.24 | LTSpice und Python                             |
| 24.06.24 | Transformatoren                                |
| 01.07.24 | Klausurvorbereitung                            |
